### PR TITLE
v4.3.1 and regenerate recipe with grayskull

### PR DESCRIPTION
**Pull request by Anthchirp**
regenerated the recipe with grayskull

* python: noarch
* `vsc*` dependencies have gone since 4.x
* ~`pyyaml` not mentioned anywhere in the code~
* `coloredlogs` and `humanfriendly` are so optional that `setup.py` doesn't even mention them
* updated project URLs
* added myself as maintainer

closes #28 and takes this project off the Python 3.9 backlog because of `noarch`

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
@conda-forge/easybuild-framework this is ready for review/merging

**Comment by Anthchirp** [comment]
@boegel I noticed that you're listed as a maintainer in the recipe, but are not part of the github team for this one. Is that on purpose?

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by boegel** [comment]
@Anthchirp I'm the lead developer for EasyBuild, but I don't have the bandwidth to also maintain the conda recipes for EasyBuild...

I'm happy to answer any questions you may have though...

`PyYAML` is (still) an optional dependency (you should check for `import yaml`).

There are some other optional dependencies for specific features of EasyBuild, like the `GitPython` and `keyring` + `keyrings.alt` Python packages (relevant for the features described at easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html), and [`archspec`](https://pypi.org/project/archspec/).

**Comment by Anthchirp** [comment]
@boegel thanks for your reply.

Thanks for the sanity check on `pyyaml` - I missed that.

I guess there are three options:
1. I could make a second package output that installs all optional dependencies, eg. `easybuild-framework-extras` if you think that is useful.
2. I could add all optional dependencies to the recipe, or
3. I can just leave it as it is at the moment.

What do you think? I hold no particular opinion on this - I don't use the package myself, I'm just trying to get downstream packages running on Python 3.9 :slightly_smiling_face:

**Comment by boegel** [comment]
Options 2 makes most sense to me, so people get an EasyBuild installation that's fully capable. There's no negative side effect of having the optional dependencies around, so I don't see why not to install it like that (but I may be missing something).

**Comment by Anthchirp** [comment]
Thank you! As I understand it EasyBuild is used in development environments, but not itself a runtime dependency of packages that make use of it. In this case I don't see any particular downside of having all optional dependencies in here.
I've left out `keyrings.alt` due to the warning, it looks like that one should be a conscious choice.

Final question: Do you want to stay on as a maintainer of the package?

**Comment by Anthchirp** [comment]
(build is now failing due to missing dependency declarations in the archspec package, fix proposed at https://github.com/conda-forge/archspec-feedstock/pull/1)

**Comment by boegel** [comment]
> Final question: Do you want to stay on as a maintainer of the package?

I'm happy to stay listed as maintainer, but I can't make strong promises w.r.t. actively helping out with keeping the package updated in `conda`... People can definitely ping me for help if needed though.

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
@conda-forge-admin, please restart ci

**Comment by Anthchirp** [comment]
Builds pass now, so @conda-forge/easybuild-framework this is ready to be merged :slightly_smiling_face:

**Pull request merged**
